# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b51aa6b17f1e5e45f840962d4b514fb09811521003076203b15c9d1ad6ad86c1d96d935a4b2a733809babd80609f992eab7982d943d248e2d709d0a6d4a97faf

test:
  secret_key_base: debab220e0734fc99474058e544a68856a82e54ad4a14b8a3e1cc9dc02fd2e56faa00d9b8742d69369228c6005d8d3480a71e94e4b69a7b2ad6dbe4deb1aa070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
